### ISSUE TITLE
App Store issues

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/Scan2Post#3]
<img width="732" alt="bildschirmfoto 2018-09-05 um 08 59 05" src="https://user-images.githubusercontent.com/4953/45076269-05be6600-b0ea-11e8-946e-131187f4c11b.png">

**Comment by zdavatz** [comment]
The second issue I partially solved with 785366495a216b529b4c4a8008f21adb1137

**Comment by bettar** [comment]
For example AmiKo OSX sets LSApplicationCategoryType to public.app-category.medical. What should it be for Scan2Post ? (see the various options in the AmiKo OSX plist file)

**Comment by zdavatz** [comment]
just pick the one that makes the most sense to you.

**Comment by zdavatz** [comment]
How about "Service"

**Comment by zdavatz** [comment]
Can we do _public.app-category.utilities_?
