### ISSUE TITLE
Server URL is not saved when you change it in the App.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/Scan2Post#8]
1. Open Scan2Post
2. In settings change Server-URL to: _https://elstage.pharmedsolutions.ch/api/1.0/insurance-card_
3. Set-User to jdoe@gmail.com
4. Login here: https://elstage.pharmedsolutions.ch/login
5. User same as under 3.
6. Password I will send you.
7. https://elstage.pharmedsolutions.ch/login
8. In the Browser got to: "Patienten" -> "Neuen Patienten erfassen"
9. Now the fields should be filled in.

**Comment by bettar** [comment]
For step 8 with Safari I need to click the hamburger icon first, in order to see a menu.

**Comment by zdavatz** [comment]
1. Open Settings
2. Enter "github.com"
3. Enter "Zeno" as User
4. Enter "Zeno" as Password.
5. Click save.
6. Stop App. Restart it again.
7. Enter above values from 2. and 3.
8. JSON string is not generated if the Password field is empty. 
9. If JSON string is generated correctly, then delete last letter of URL and resave.

Create JSON string with and without password.

**Comment by zdavatz** [comment]
seems to working now.
